# Generated by Django 4.1.7 on 2023-08-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_logentry_log_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
