# Generated by Django 4.1.7 on 2023-08-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
